config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :jobs
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/job.rb
class Job < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!

end

app/controllers/jobs_controller.rb
class JobsController < ApplicationController
  before_action :find_job, only: [:show, :edit, :update, :destroy]

  def index
    if params[:query].present?
      sql_query = "role ILIKE :query OR location ILIKE :query"
      @jobs = Job.where(sql_query, query: "%#{params[:query]}%")
    else
      @jobs = Job.all
    end
  end

  def show
  end

  def new
    @job = Job.new
  end

  def create
    @job = Job.new(job_params)
    @job.user_id = current_user.id
    @job.save!
    redirect_to jobs_path(@job)
  end

  def edit
  end

  def update
    if @job.update(job_params)
      redirect_to jobs_path(@job)
    else
      render :new
    end
  end

  def destroy
    @job.destroy
    redirect_to jobs_path(@job)
  end

  private

  def find_job
    @job = Job.find(params[:id])
  end

  def job_params
    params.require(:job).permit(:role, :location, :rate, :contract, :sector)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [ :home ]

  def home
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/jobs/_form.html.erb
<form class = "simple-form" method = "POST" action = "/jobs">
<%= form_for(@job) do |f| %>
  <div class = "label"><%= f.label :role %></div>
  <div class = "input-box"><%= f.text_field :role %> </div>
  <div class = "label"><%= f.label :location %></div>
  <div class = "input-box"><%= f.text_field :location%></div>
  <div class = "label"><%= f.label :contract %></div>
  <div class = "input-box"><%= f.text_field :contract %></div>
  <div class = "label"><%= f.label :rate %></div>
  <div class = "input-box"><%= f.text_field :rate%></div>
  <div class = "label"><%= f.label :sector %></div>
  <div class = "input-box"><%= f.text_field :sector %></div>
  <%= f.submit %>
<% end %> </form>

app/views/jobs/edit.html.erb
<%= render 'form' %>

app/views/jobs/index.html.erb
<ul>
  <% @jobs.each do |job| %>
    <li><h2><%= job.role %> - <%= job.location %> </h2>
    <% if job.contract == "contract" %>
      <h4><%= job.sector.capitalize %> - £<%= job.rate %> Per Shift </h4>
    <% else  %>
      <h4><%= job.sector.capitalize %> - £<%= job.rate %> Per Annum </h4>
    <% end %>
    <p> If interested please contact <%= job.user.name %> </p>
    <% if (current_user.id == job.user_id) || (current_user.id ==9 ) %>
    <p> <%=(link_to 'Edit', edit_job_path(job)) %>
    <%= link_to " Delete",
            job_path(job),
            method: :delete,
            data: { confirm: "Are you sure?" } %></p></li>
  <% end %>
  <% end %>
</ul>
<% if current_user.company == "keyman" %>
    <p> <%=(link_to 'New Job', new_job_path(@jobs)) %></p>
<% end %>

app/views/jobs/new.html.erb
<h3> New Job </h3>
<%= render 'form' %>

app/views/jobs/show.html.erb
<h2><%= @job.role %></h2>
<p><%= @job.location %></p>
<p><%= @job.contract %></p>
<p><%= @job.rate %></p>
<p><%= @job.sector %></p>
<p><%= @job.user.name %></p>

    <% if job.user_id == current_user.id %>
    <p> <%=(link_to 'Edit', edit_job_path(job)) %>
    <%= link_to " Delete",
            job_path(job),
            method: :delete,
            data: { confirm: "Are you sure?" } %></p></li>
  <% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Recap</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
  </head>

  <body>
    <%= render 'shared/navbar' %>
    <%= render 'shared/flashes' %>

    <%= yield %>
  </body>
</html>

app/views/pages/home.html.erb
<%= image_tag("london.jpeg", class: "bg-image shadow-2-strong", id:"bg", alt: "an image of a london skyline") %>
<div class = "message"> <h3> Unlock your Future <h3>
<h3> with Keyman <h3> </div>

<div class = "search" >
  <%= form_tag jobs_path, method: :get do %>
  <%= text_field_tag :query,
    params[:query],
    class: "form-control",
    placeholder: "Find a Job"
  %>
  <%= submit_tag "Search", class: "btn btn-primary" %>
<% end %>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <%= link_to "#", class: "navbar-brand" do %>
    <div id= "logo-img"> <%= image_tag "Keyman Logo.png" %> </div>
  <% end %>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>


  <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav">
      <li class="nav-item active">
        <a class="nav-link" href="#"><%= link_to 'Home', root_path %> <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#"><%= link_to 'Featured Jobs', jobs_path %></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#"><%= link_to 'Clients', "2" %></a>
      </li>
      <li class="nav-item">
        <a class="nav-link " href="#"><%= link_to 'Candidates', "d"%></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#"><%= link_to 'Projects', "d"%></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#"><%= link_to 'Key Values', "d"%></a>
      </li>
    </ul> <br>
    <ul class="navbar-nav mr-auto">
      <% if user_signed_in? %>
        <li class="nav-item dropdown">
          <%= image_tag "https://kitt.lewagon.com/placeholder/users/ssaunier", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
            <%= link_to "Action", "#", class: "dropdown-item" %>
            <%= link_to "Another action", "#", class: "dropdown-item" %>
            <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
          </div>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to "Login", new_user_session_path, class: "nav-link" %>
        </li>
      <% end %>
    </ul>
  </div>
</div>